backend:
  name: test-repo
  repo: el7oot777/el7oot-store
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "products.json"
        label: "Products"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Price", name: "price", widget: "number"}
              - {label: "Sizes", name: "sizes", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
